name: Publish to PyPi
on: 
  release:
    types: [published]

jobs:
  test:
    uses: dreoilin/pygmid/.github/workflows/run-tests.yml@main
  build:
    name: Build and upload python distributions
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        cache: pip
    - run: pip install build --user
    - run: python3 -m build --sdist --wheel --outdir dist/
    - name: Upload distribution
      uses: actions/upload-artifact@v3
      with:
        name: pygmid-dist
        path: dist/

  publish-pypi:
    name: Publish package distribution to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: pypi
      url: https://pypi.org/p/pygmid
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: pygmid-dist
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1